// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB-LHCVHdRdC6OyBnCUu6z2EJkKwbd1rc',
    appId: '1:616652766666:web:2c8d9f5ebf068287416333',
    messagingSenderId: '616652766666',
    projectId: 'skillmatch-68bc1',
    authDomain: 'skillmatch-68bc1.firebaseapp.com',
    storageBucket: 'skillmatch-68bc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvBSpgAx9QSzBpjmwFUUwnHCabTfTuMS0',
    appId: '1:616652766666:android:9b96ea17a104daa4416333',
    messagingSenderId: '616652766666',
    projectId: 'skillmatch-68bc1',
    storageBucket: 'skillmatch-68bc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjpoge0Z68oAUgF-tXPWVwtiAGvpu7D7E',
    appId: '1:616652766666:ios:780abc40d075695b416333',
    messagingSenderId: '616652766666',
    projectId: 'skillmatch-68bc1',
    storageBucket: 'skillmatch-68bc1.firebasestorage.app',
    iosBundleId: 'com.example.skillmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjpoge0Z68oAUgF-tXPWVwtiAGvpu7D7E',
    appId: '1:616652766666:ios:780abc40d075695b416333',
    messagingSenderId: '616652766666',
    projectId: 'skillmatch-68bc1',
    storageBucket: 'skillmatch-68bc1.firebasestorage.app',
    iosBundleId: 'com.example.skillmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB-LHCVHdRdC6OyBnCUu6z2EJkKwbd1rc',
    appId: '1:616652766666:web:4d709d040dc07c3b416333',
    messagingSenderId: '616652766666',
    projectId: 'skillmatch-68bc1',
    authDomain: 'skillmatch-68bc1.firebaseapp.com',
    storageBucket: 'skillmatch-68bc1.firebasestorage.app',
  );
}
